python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Chinatown --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset SonyAIBORobotSurface1 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ItalyPowerDemand --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset MoteStrain --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset SonyAIBORobotSurface2 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset TwoLeadECG --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset SmoothSubspace --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ECGFiveDays --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Fungi --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset CBF --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset BME --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset UMD --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset DiatomSizeReduction --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset DodgerLoopWeekend --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset DodgerLoopGame --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset GunPoint --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Coffee --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset FaceFour --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset FreezerSmallTrain --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ArrowHead --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ECG200 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Symbols --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ShapeletSim --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset InsectEPGSmallTrain --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset BeetleFly --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset BirdChicken --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ToeSegmentation1 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ToeSegmentation2 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Wine --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Beef --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Plane --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset OliveOil --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset SyntheticControl --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset PickupGestureWiimoteZ --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ShakeGestureWiimoteZ --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset GunPointMaleVersusFemale --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset GunPointAgeSpan --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset GunPointOldVersusYoung --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Lightning7 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset DodgerLoopDay --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset PowerCons --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset FacesUCR --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Meat --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Trace --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset MelbournePedestrian --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset MiddlePhalanxTW --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset DistalPhalanxOutlineAgeGroup --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset MiddlePhalanxOutlineAgeGroup --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ProximalPhalanxTW --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ProximalPhalanxOutlineAgeGroup --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset DistalPhalanxTW --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Herring --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Car --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset InsectEPGRegularTrain --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset MedicalImages --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Lightning2 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset FreezerRegularTrain --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Ham --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset MiddlePhalanxOutlineCorrect --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset DistalPhalanxOutlineCorrect --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ProximalPhalanxOutlineCorrect --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Mallat --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset InsectWingbeatSound --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Rock --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset GesturePebbleZ1 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset SwedishLeaf --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset CinCECGTorso --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset GesturePebbleZ2 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Adiac --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ECG5000 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset WordSynonyms --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset FaceAll --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset GestureMidAirD2 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset GestureMidAirD3 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset GestureMidAirD1 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ChlorineConcentration --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset HouseTwenty --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Fish --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset OSULeaf --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset MixedShapesSmallTrain --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset CricketZ --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset CricketX --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset CricketY --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset FiftyWords --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Yoga --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset TwoPatterns --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset PhalangesOutlinesCorrect --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Strawberry --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ACSF1 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset AllGestureWiimoteY --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset AllGestureWiimoteX --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset AllGestureWiimoteZ --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Wafer --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset WormsTwoClass --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Worms --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Earthquakes --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Haptics --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Computers --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset InlineSkate --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset PigArtPressure --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset PigCVP --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset PigAirwayPressure --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Phoneme --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ScreenType --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset LargeKitchenAppliances --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset SmallKitchenAppliances --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset RefrigerationDevices --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset UWaveGestureLibraryZ --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset UWaveGestureLibraryY --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset UWaveGestureLibraryX --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ShapesAll --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset Crop --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset SemgHandGenderCh2 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset EOGVerticalSignal --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset EOGHorizontalSignal --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset MixedShapesRegularTrain --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset SemgHandMovementCh2 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset SemgHandSubjectCh2 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset PLAID --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset UWaveGestureLibraryAll --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset ElectricDevices --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset EthanolLevel --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset StarLightCurves --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset NonInvasiveFetalECGThorax1 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset NonInvasiveFetalECGThorax2 --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset FordA --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset FordB --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
python -u /data/root/data/chenrj/经典方法/deep\ learning/ts2vec-main/train.py --dataset HandOutlines --loader UCR --batch-size 8 --repr-dims 320 --max-threads 8 --seed 42 --eval
